<?php
/**
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$_postCollection = $block->getPostCollection();
?>
<?php if (!$_postCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find posts matching the selection.') ?></div></div>
<?php else: ?>
<?php
$descLength = $block->getData('desc_length')?:120;
$width = $block->getData('thumb_width')?:450;
$height = $block->getData('thumb_height')?:450;
$imgRatio = $width/$height;
$dateFormat = $this->getData('date_format')?:'m/d/Y';
$imgHelper = $this->helper('Codazon\ThemeLayoutPro\Helper\Image');//$imgHelper = $this->helper('Magefan\Blog\Helper\Image');
$showImage = $this->isShow('featured_img');
$showTitle = $this->isShow('title');
$showShortContent = $this->isShow('short_content');
$showPublishTime = $this->isShow('publish_time');
$showAuthor = $this->isShow('author');
$showCategory = $this->isShow('category');

$totalRows = (int)$this->getData('total_rows')?:1;
$showSlider = $this->getData('show_slider');
$widget = ['themewidgets' => [
    'codazon.slider' => [
        'sliderConfig' => $this->getSliderData(),
        'sameHeight' => ['']
    ]
]];
?>
<div class="post-grid-16 wrapper grid blog-post-grid" style="--img-ratio:<?= $imgRatio ?>;--canvas-ratio:<?= $imgRatio ?>">
    <div class="items post-items<?= $showSlider?' owl-carousel':''?>" <?php if ($showSlider) : ?>data-mage-init='<?= json_encode($widget) ?>'<?php endif ?>>
    <?php foreach ($_postCollection as $_post) : ?>
        <?php
            $_postName = $block->escapeHtml($_post->getTitle(), true, null);
            $_postUrl = $_post->getPostUrl();
        ?>
        <div class="item post-item banner-style41">
            <div class="i-inner">
                <div class="i-top">
                    <?php if ($showImage) : ?>
                    <?php
                    $_postFeatured = $_post->getData('featured_img');
                    $_postImage = '';
                    if ($_postFeatured) {
                        $_postImage = (string)$imgHelper->init($_postFeatured)->setBaseDir('blog/cache/')->keepFrame(false)->resize($width, null);
                    }
                    ?>
                    <div class="i-wrap">
                        <a href="<?= $_postUrl ?>" class="i-img img-cover">
                            <?php if ($showSlider) : ?>
                            <img class="owl-lazy img-responsive" data-src="<?= $_postImage ?>" alt="<?= strip_tags($_postName) ?>" />
                            <?php else : ?>
                            <img class="img-responsive" src="<?= $_postImage ?>" alt="<?= strip_tags($_postName) ?>" loading="lazy" />
                            <?php endif ?>
                        </a>
                    </div>
                    <div class="i-go-wrap"><a class="i-go" href="<?= $_postUrl ?>"><span></span></a></div>
                    <?php endif ?>
                    <?php if ($showCategory) : ?>
                    <?php $category = $_post->getParentCategory(); ?>
                    <?php if ($category->getId()) : ?>
                    <a class="post-category" href="<?= $category->getCategoryUrl() ?>"><?= $category->getTitle() ?></a>
                    <?php endif ?>
                    <?php endif ?>
                </div>
                <div class="post-bottom">
                    <?php if ($showTitle) : ?>
                    <div class="post-title">
                        <a class="post-item-link line-clamp" title="<?= $_postName ?>" href="<?= $_postUrl ?>"><?= $_postName; ?></a>
                    </div>
                    <?php endif ?>
                    <?php if ($showPublishTime || $showAuthor) : ?>
                    <div class="post-extra">
                    <?php if ($showPublishTime) : ?>
                        <div class="post-date"><?= $block->getPostedOn($_post, $dateFormat); ?></div>
                    <?php endif ?>
                    <?php if ($showAuthor) : ?>
                    <div class="post-author"><?= $_post->getAuthor() ? '<a href="' . $_post->getAuthor()->getUrl() . '">' . $_post->getAuthor()->getName() . '</a>' : '' ?></div>
                    <?php endif ?>
                    </div>
                    <?php endif ?>
                    <?php if ($showShortContent) : ?>
                    <div class="post-desc">
                        <?= $block->subString($_post->getShortContent(), $descLength); ?>
                    </div>
                    <?php endif ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
</div>
<?php endif ?>